apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: testapp-ing
  namespace: testapp
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`guest.80.158.49.239.sslip.io`)
      services:
        - kind: Service
          name: kustomize-guestbook-ing
          passHostHeader: true
          namespace: testapp
          port: 80
  tls:  
    secretName: testapp-cert 
